{
 "title": "Flask Application Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Duration (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(flask_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "flask_http_request_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Request rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "flask_http_request_total", "legendFormat": "__auto" }
   ]
  }
 ]
}